# Generated by Django 3.1.2 on 2020-11-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainactivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('teamslink', models.TextField()),
                ('programmed_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityrecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_status', models.IntegerField(choices=[(0, 'Terminada'), (1, 'En Proceso')], default=1)),
                ('process_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disabled', models.BooleanField(default=False)),
                ('main_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturacyberCore.mainactivitymodel')),
            ],
        ),
    ]
