# Generated by Django 3.1.2 on 2020-11-12 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberAuth', '0005_auto_20201111_1715'),
        ('culturacyberCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('activity_status', models.IntegerField(choices=[(0, 'Terminada'), (1, 'En Proceso')], default=1)),
                ('teamslink', models.TextField()),
                ('programmed_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturacyberAuth.clientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='moduleModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('client', models.ManyToManyField(blank=True, to='culturacyberAuth.clientModel')),
            ],
        ),
        migrations.CreateModel(
            name='taskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('task_status', models.IntegerField(choices=[(0, 'Terminada'), (1, 'En Proceso'), (2, 'Corregida'), (3, 'Rechazada')], default=1)),
                ('teamslink', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturacyberCore.activitymodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityrecordModel',
        ),
        migrations.DeleteModel(
            name='MainactivityModel',
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturacyberCore.modulemodel'),
        ),
    ]
