# Generated by Django 3.1.2 on 2020-11-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainactivitymodel',
            name='teamslink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
