# Generated by Django 3.1.2 on 2020-11-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0003_auto_20201112_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='programmed_date',
            field=models.DateTimeField(),
        ),
    ]
