# Generated by Django 3.1.2 on 2020-11-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0005_auto_20201112_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='activity_status',
            field=models.IntegerField(choices=[(0, 'Terminada'), (1, 'En Proceso'), (2, 'En Espera')], default=2),
        ),
    ]
