# Generated by Django 3.1.2 on 2020-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0009_auto_20201123_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='updated_for',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='name',
            field=models.IntegerField(choices=[(0, 'Poster Conocimiento'), (1, 'Poster Actitud'), (2, 'Poster Comportamiento'), (3, 'Infografía'), (4, 'Newsletter'), (5, 'Noticia'), (6, 'Vídeo'), (7, 'Actividad/Ejercicio Phishing'), (8, 'Test'), (9, 'Prueba'), (10, 'Encuesta')], default=0),
        ),
    ]
