# Generated by Django 3.1.3 on 2020-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0010_auto_20201123_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_module_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamslink', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='modulemodel',
            name='client',
        ),
    ]
