# Generated by Django 3.1.3 on 2020-11-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0012_auto_20201126_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_module_model',
            name='teamslink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
