# Generated by Django 3.1.3 on 2020-11-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0013_auto_20201126_1614'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client_module_model',
            table='culturacyberCore_moduleModel_client',
        ),
    ]
