# Generated by Django 3.1.3 on 2020-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0014_auto_20201126_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_module_model',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
