# Generated by Django 3.1.3 on 2020-12-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0015_client_module_model_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_module_model',
            name='teamslink',
            field=models.TextField(default='-'),
        ),
    ]
