# Generated by Django 3.1.3 on 2020-12-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberCore', '0016_auto_20201204_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_module_model',
            name='teamslink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
