# Generated by Django 3.1.2 on 2020-11-11 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='cultureteam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='culturacyberAuth.clientmodel'),
        ),
    ]
