# Generated by Django 3.1.2 on 2020-11-11 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('culturacyberAuth', '0003_auto_20201111_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturacyberAuth.clientmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend', to='auth.user'),
        ),
    ]
