# Generated by Django 3.1.2 on 2020-11-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberAuth', '0005_auto_20201111_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='description',
            field=models.TextField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
