# Generated by Django 3.1.2 on 2020-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberAuth', '0006_auto_20201113_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
