# Generated by Django 3.1.2 on 2020-11-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberAuth', '0008_auto_20201113_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='teamslink',
            field=models.TextField(default='-'),
        ),
    ]
