# Generated by Django 3.1.2 on 2020-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberAuth', '0009_clientmodel_teamslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='teamslink',
            field=models.TextField(),
        ),
    ]
