# Generated by Django 3.1.2 on 2020-11-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberAuth', '0010_auto_20201116_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
    ]
