# Generated by Django 3.1.3 on 2020-12-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberAuth', '0011_remove_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
