# Generated by Django 3.1.3 on 2020-12-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberAuth', '0012_auto_20201207_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='verified_account',
            field=models.BooleanField(default=False),
        ),
    ]
