# Generated by Django 3.1.1 on 2020-09-30 20:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='contentbody',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
