# Generated by Django 3.1.1 on 2020-09-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberPost', '0002_auto_20200930_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='postimg',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
