# Generated by Django 3.1.1 on 2020-09-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberPost', '0003_postmodel_postimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='postimg',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
