# Generated by Django 3.1.1 on 2020-10-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberPost', '0005_auto_20201005_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='postimg',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='attachedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturacyberPost.postmodel')),
            ],
        ),
    ]
