# Generated by Django 3.1.1 on 2020-10-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturacyberPost', '0006_auto_20201005_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
